// `panic`は通常、何か予期していない間違いが発生したことを示します。
// ほとんどの場合、普通の操作で起きるべきではないエラーについて早く失敗させるために使います。
// また、エラーをきれいに処理する準備ができていない場合にも使います。

package main

import "os"

func main() {

    // このサイトではpanicは予期しないエラーをチェックするために使っています。
    // この例はこのサイトで唯一panicのために設計されたプログラムです。
    panic("a problem")

    // panicは関数が処理できないエラーを返したときに使うのが一般的です。
    // ここでは新しいファイルを作成するときに予期しないエラーが発生した場合に`panic`しています。
    _, err := os.Create("/tmp/file")
    if err != nil {
        panic(err)
    }
}
